apiVersion: v2
name: Platomics 
version: 1.0.0

dependencies:
  - name: postgresql
    version: 16.0.1
    repository: oci://registry-1.docker.io/bitnamicharts

  - name: kube-prometheus-stack
    version: 64.0
    repository: https://prometheus-community.github.io/helm-charts

  # - name: prometheus-postgres-exporter
  #   repository: https://prometheus-community.github.io/helm-charts
  #   version: 6.0.0
