apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2
  labels:
    app: db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      restartPolicy: Always
      containers:
        - image: nginx:1.16.1-alpine
          name: db2
          ports:
            - containerPort: 80
              name: http
          envFrom:
          - secretRef:
              name: db2-secret